### ISSUE TITLE
너무 난잡해서 마크다운 마저 난독화 한줄 알았어요.

### ISSUE THREAD

**Issue by sunwoo0706** [sunrabbit123/sunrabbit123#1]
좀 줄여 니 못하는건 왜 넣어 놓은거야

**Comment by sunrabbit123** [comment]
그거 수정할려고 한건데 귀찮아서 안하는 중인디야
난 화려한게 좋다

**Comment by sunrabbit123** [comment]
그리고 interseted in은 흥미가지고 있는이여서 나중에 배울려고 써놓은것들인디?

**Comment by sunwoo0706** [comment]
넌 그래도 이슈를 보긴 보네
딴 애들은 있는지도 모르더라
